package py.gov.jem.expedientes.models;
// Generated 19/10/2019 03:56:13 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * ValidacionesReseteo generated by hbm2java
 */
@Entity
@Table(name = "validaciones_reseteo")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "ValidacionesReseteo.findAll", query = "SELECT p FROM ValidacionesReseteo p")
    , @NamedQuery(name = "ValidacionesReseteo.findByHash", query = "SELECT p FROM ValidacionesReseteo p WHERE p.hash = :hash")
    , @NamedQuery(name = "ValidacionesReseteo.findByHashFechaHoraCaducidad", query = "SELECT p FROM ValidacionesReseteo p WHERE p.hash = :hash and p.fechaHoraCaducidad > :fechaHoraCaducidad")})
public class ValidacionesReseteo implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "hash")
    private String hash;
    @JoinColumn(name = "persona", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Personas persona;
    @JoinColumn(name = "empresa", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Empresas empresa;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "email")
    private String email;
    @Basic(optional = false)
    @NotNull
    @Column(name = "fecha_hora_alta")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fechaHoraAlta;
    @Basic(optional = false)
    @NotNull
    @Column(name = "fecha_hora_caducidad")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fechaHoraCaducidad;
    @Basic(optional = true)
    @Column(name = "fecha_hora_reseteo")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fechaHoraReseteo;

    public ValidacionesReseteo() {
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public Personas getPersona() {
        return persona;
    }

    public void setPersona(Personas persona) {
        this.persona = persona;
    }

    public Empresas getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresas empresa) {
        this.empresa = empresa;
    }

    public String getReseteo() {
        return email;
    }

    public void setReseteo(String email) {
        this.email = email;
    }

    public Date getFechaHoraAlta() {
        return fechaHoraAlta;
    }

    public void setFechaHoraAlta(Date fechaHoraAlta) {
        this.fechaHoraAlta = fechaHoraAlta;
    }

    public Date getFechaHoraCaducidad() {
        return fechaHoraCaducidad;
    }

    public void setFechaHoraCaducidad(Date fechaHoraCaducidad) {
        this.fechaHoraCaducidad = fechaHoraCaducidad;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getFechaHoraReseteo() {
        return fechaHoraReseteo;
    }

    public void setFechaHoraReseteo(Date fechaHoraReseteo) {
        this.fechaHoraReseteo = fechaHoraReseteo;
    }

    @Override
    public int hashCode() {
        int hash2 = 0;
        hash2 += (hash != null ? hash.hashCode() : 0);
        return hash2;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Estados)) {
            return false;
        }
        ValidacionesReseteo other = (ValidacionesReseteo) object;
        if ((this.hash == null && other.hash != null) || (this.hash != null && !this.hash.equals(other.hash))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return hash;
    }
    
}
